#!/bin/ksh

case $1 in

-d)
if [ -d $2 ]
then
   echo "Directory '$2' found"
else
   echo "'$2' is no directory"
fi;;

-f)
if [ -f $2 ]
then 
	echo " File '$2' found"
else
	echo " '$2' is no regular file"
fi;;
esac
